# Generated by Django 5.1.4 on 2025-01-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reservation_system', '0002_moviegenre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
