# Generated by Django 5.1.4 on 2025-01-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reservation_system', '0005_remove_showtime_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showtime',
            old_name='start_time',
            new_name='start_show_time',
        ),
        migrations.AddField(
            model_name='showtime',
            name='end_show_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
