# Generated by Django 5.1.4 on 2025-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reservation_system', '0006_rename_start_time_showtime_start_show_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='is_active',
        ),
        migrations.AddField(
            model_name='showtime',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
