# Generated by Django 5.1.4 on 2025-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reservation_system', '0008_alter_showtime_end_show_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='show_time_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
